NAME		= so_long

CC			= gcc

CFLAG		= -Wall -Wextra -Werror -g -fsanitize=address

MLX_FLAG	= -Lmlx_linux -lmlx_linux -Imlx_linux -lXext -lX11 -lm -lz

MLX_PATH	= ./mlx_linux

SRC =	so_long.c \
		check_map.c \
		check_map2.c \
		display_map.c \
		error_msg.c \
		game_end.c \
		game_init.c \
		get_next_line_utils.c \
		get_next_line.c \
		./utils/utils1.c \
		
SRC_OBJ		= $(SRC:.c=.o)

all:	$(NAME)

.c.o:
			${CC} ${CFLAGS} -Imlx_linux -c $< -o ${<:.c=.o}

$(NAME):	$(SRC_OBJ)
		make -C ${MLX_PATH}
		$(CC) $(CFLAG) -o $(NAME) $(SRC_OBJ) $(MLX_FLAG) 

clean:
				make -C ${MLX_PATH} clean
				rm -f ${SRC_OBJ}

fclean: 		clean
				make -C ${MLX_PATH} clean
				rm -f ${NAME}

re:         	fclean all

.PHONY:        all clean fclean re
