# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fmonbeig <fmonbeig@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/28 12:05:23 by fmonbeig          #+#    #+#              #
#    Updated: 2021/07/28 14:40:19 by fmonbeig         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =	so_long

CC =	gcc

CFLAG =	-Wall -Wextra -Werror -g -fsanitize=address

OFLAG =	-Lmlx_linux -lmlx_linux -L/usr/lib -Imlx_linux -lXext -lX11 -lm -lz

MLX_PATH=	mlx_linux

SRC =	 main.c

SRC_OBJ =	$(SRC:.c=.o)

all:	$(NAME)

$(NAME):	$(SRC_OBJ)
	$(CC) $(CFLAG) $(SRC_OBJ) $(OFLAG) $(NAME)

%.o:	%.c
	$(CC) $(CFLAG) -I/usr/include -Imlx_linux -O3 -c $< -o $@

clean:
				make -C ${MLX_PATH} clean
				${RM} ${SRC_OBJ}

fclean: 		clean
				rm -f ${NAME}

re:         	fclean all

.PHONY:        all clean fclean re lmake
